### ISSUE TITLE
Insta-Death when player damage >= player hp

### ISSUE THREAD

**Issue by DomenTV** [andrei923/LeafBattleRoyale#7]
I discovered this issue a long time ago & I posted about it on the spigot forum, but just wanted to be more clear & attach proof as well as my simple unelegant fix. Throughout setting up the server & actually playing the game-mode; there would regularly be issues with players dying way too fast. Sometimes it was really obvious like getting one-shotted with a bow that should have done just 2 hearts of damage considering the full diamond gear. Similar issues would occur in mele fights as well where players would be fighting for a prolonged period of time (dealing only about 1-3 hearts of damage per hit) & dying out of nowhere when they still had half of their HP left.
First I thought it was an issue with 1.14.4 version of Minecraft or because the "Critical hit" damage, but got all of that sorted out & it was still happening. Finally I managed to isolate the issue in testing, where outside of the game-mode a power 5 bow was able to deal 2-3 hearts of damage on a player (every single time & ofc they had enchanted diamond gear), but in-game a fully charged power 5 bow would always insta-kill a player even with the best gear available in the br game (in my case, full diamond, projectile protection 3) 
**The issue:**
 I noticed that in the code, there is a part that asks "if damage >= health of victim:" & if it is, the player is killed. This is an issue as it does not take armor or potion effects into consideration; so a fully charged power 5 bow that deals 12,5 hearts of damage would always insta-kill the player no matter the armor or potion effects. I made a simple fix & posted the code down bellow. It is not the most elegant fix, but it does work.
Anyways, saw that this issue was still present in the new 0.2.1 release & just wanted to make a proper ticket; great code, great stuff, have a nice day!:D

![image](https://user-images.githubusercontent.com/28386835/88458102-bf17b780-ce8b-11ea-9e07-2423367c6d33.png)
![image](https://user-images.githubusercontent.com/28386835/88458129-0aca6100-ce8c-11ea-8e1d-1c1fe1e227fc.png)

![image](https://user-images.githubusercontent.com/28386835/88458112-d5be0e80-ce8b-11ea-85f6-62e8a3fba435.png)

**Comment by andrei923** [comment]
https://github.com/andrei923/LeafBattleRoyale/commit/e11fec9664d652eda27c7dfa2fa1c84887cec294
